### ISSUE TITLE
Orientation media query breaks output

### ISSUE THREAD

**Issue by mrgnou** [panec/postcss-mq-optimize#5]
When using orientation css media query, the optimiser fails to correctly render the output.

```
@media (max-width: 1024px) and (orientation: landscape) {
	...
}
```

Will be compiled as:
```
@media (max-width:1024px)and) and (orientation:landscape){
	...
}
```

**Comment by panec** [comment]
Works for me. I added a test case for this one and I cannot replicate the problem.

**Comment by stephensabatini** [comment]
Strangely enough we had this problem too but with the first parameter being a min-width and the second being a max-width it was adding that "and)". We've disabled the plugin for now since it fixes it. Seems to not be a SASS mixin issue as we even did it using straight CSS to write the media query. We'll probably wind up circling back around to this issue and evaluating if it's even worth trying to fix later on due to bandwidth. If we do circle back and find anything I'll try to report here. Just wanted to say we had it too.

**Comment by HendrikWismans** [comment]
We have the same problem. And found the issue! If there are no spaces before and after the "and" it goes wrong. A css minifier can to this sometimes before it pass through postcss-mq-optimize. In our case, sass-loader in webpack was done first and minified the css code.

**Works:**
`@media(min-width: 1024px) and (max-width: 1023px){body{background:aqua}}`

**Doesn't work**
`@media(min-width: 104px)and(max-width: 1023px){body{background:aqua}}`

I don't have access to make a pull request. @panec You can fix the issue when you add the following line on rule 27 in index.js. 

`query = query.replace('and', ' and ');` 
(after `postcss.list.comma(queryList).forEach(function (query) {`)

**Comment by panec** [comment]
Done. Version 1.1.1 will add those spaces as you requested

**Comment by Teddytrombone** [comment]
We have the same issue. Our mediaquery: `@media print,screen and (min-width: 48em)and (max-width: 74.99875em) {}`. I guess the workaround with `query = query.replace('and', ' and ');` only replaces the first occurence of `and`. Could you extend this to replace every occurence?
